### ISSUE TITLE
F1 disorder loader also loading F10

### ISSUE THREAD

**Issue by HLasse** [Aarhus-Psychiatry-Research/psycop-common#1058]
https://github.com/Aarhus-Psychiatry-Research/psycop-common/blob/4f6736de46c198f335a68365e43cd44fd5158573/psycop/common/feature_generation/loaders/raw/load_diagnoses.py#L553

Doing revisions for the ECT paper and double checking some feature importance, I noticed that the `wildcard=True` parameter in the f1_disorders loader might cause it to also load F10 diagnoses. Can someone check (and fix) if this is the case?

**Comment by sarakolding** [comment]
@HLasse I think this is the intended behaviour, since f1 contains f10-f19 as subgroups, and as far as I can tell, f1 does not exist as a diagnosis on its own. Also possible that I'm confused, feel free to give me a call or send me a message if this doesn't make sense.

**Comment by sarakolding** [comment]
no probs ;-)
