### ISSUE TITLE
inv install does not work

### ISSUE THREAD

**Issue by KennethEnevoldsen** [Aarhus-Psychiatry-Research/psycop-common#241]
1. Inv install only install dev requirements
2. an osError is raised due to access denied (of an inv.exe file)

@MartinBernstorff when you have the time we should have a look it at (it shouldn't be such that only a few people can do this. Everyone should be able to set things up.

**Comment by MartinBernstorff** [comment]
> an osError is raised due to access denied (of an inv.exe file)

I'm not sure this is solvable by us, but rather it's a Windows permission error. Windows permissions are outside of my competency, unfortunately, and probably managed by hospital IT through Microsoft Domains/Active Directory/LDAP. 

However, we can have everyone be able to set everything up, as long as they install all the requirements from requirements.txt.

> Inv install only install dev requirements

Agreed, that's a problem! My suggestion would be migrating to containers for dev environments, and also using those containers for tests. This ensures that we can truly keep environments synced. That said, it also incurs a bit of a performance penalty. Probably we should have a chat about it?

**Comment by KennethEnevoldsen** [comment]
@MartinBernstorff let us discuss this one tomorrow

**Comment by KennethEnevoldsen** [comment]
fixed in #256 I presume
