### ISSUE TITLE
Add sep tokens

### ISSUE THREAD

**Issue by KennethEnevoldsen** [Aarhus-Psychiatry-Research/psycop-common#251]
![Image](https://github.com/Aarhus-Psychiatry-Research/psycop-common/assets/8526086/b485d369-f828-4072-96fb-506dd0de99a4)

**Comment by KennethEnevoldsen** [comment]
@MartinBernstorff. I looked through the paper on this one, we do need the SEP tokens (though I think they aren't needed), however to add that we need to add visit

**Comment by MartinBernstorff** [comment]
See #252.
