### ISSUE TITLE
Add visits to data structure

### ISSUE THREAD

**Issue by KennethEnevoldsen** [Aarhus-Psychiatry-Research/psycop-common#252]
We need to add visits to the data structure to add us to create the sep tokens (#251). We should also change the segments such that they match with visit instead of n within the sequence.

I am unsure how this data is structured. @MartinBernstorff we can probably find a reasonable solution tomorrow.

**Comment by MartinBernstorff** [comment]
We probably want @sarakolding on this is well; I don't think we have a similar concept of a "visit" as they do, but Sara knows more about LPR2/LPR3 than I do.

**Comment by MartinBernstorff** [comment]
@KennethEnevoldsen contacts Sara. For now, we'll train without a 'visit' concept.

**Comment by MartinBernstorff** [comment]
@sarakolding og jeg snakkede os frem til, at vi bruger definitionen "slutdato indenfor samme kalenderdato" som vores "kontakt-koncept". Jeg regner med at kigge på det i morgen 👍

**Comment by MartinBernstorff** [comment]
@frillecode @KennethEnevoldsen Did we end up adding this, or just assuming that 1 A-diagnosis ≈ 1 visit? I'm okay with that assumption 👍

**Comment by KennethEnevoldsen** [comment]
We decided that the other thing was better for the narrative

**Comment by MartinBernstorff** [comment]
Let's start with the simplest thing; using a-diagnoses as visit boundaries. This also means we don't have to implement #251.
