### ISSUE TITLE
replicate behrt filtering

### ISSUE THREAD

**Issue by KennethEnevoldsen** [Aarhus-Psychiatry-Research/psycop-common#259]
they filter on:

- [ ] quality (do we have quality of EHR - they have a flag)
- [ ] linkage to HES (hospital episode statistics i.e. secondary care)
- [ ] at least five visits (this one is probably also reasonable for us)

We can discuss it here.

**Comment by KennethEnevoldsen** [comment]
I assume we should filter in >5 visits. I am quite sure we don't have quality and I am not sure about HES (@MartinBernstorff, @sarakolding)?

**Comment by sarakolding** [comment]
1. Yes, I also assume we should filter >5 visits.

2. From a quick glance, it looks like the CPRD’s quality flag relies on:
- All data elements are of the correct type, length and format.
- Duplicate records are identified and removed.
- That all event records link to a patient.
- Consistency of key variables including date of birth, practice registration date and transfer out date.

I suspect that Bettina/BI has taken care of most of these for us. The two middle ones I think would be easy to check (i.e. that there are no duplicate events and that there are no dw_ek_borger = -1).

3. As far as I understand, what we have is equivalent to HES (secondary care). What er don't have is data from GP (primary care).

**Comment by KennethEnevoldsen** [comment]
That sounds great, we should implement filters for 1 and 2 then.

**Comment by MartinBernstorff** [comment]
Is this filtering for pre-training, fine-tuning, or both? :-)

> All data elements are of the correct type, length and format.
Is enforced by the SQL-database before write AFAIK.

> Duplicate records are identified and removed
Seems easy to do, so we should.

> That all event records link to a patient.
This is done by Bettina; we only get the diagnoses for the patients in our cohort, not all diagnoses from the entire hospital system. 

Awesome that you raised this, @KennethEnevoldsen!

**Comment by MartinBernstorff** [comment]
I'll check that we don't have any duplicate records #261.

I'll also check whether they use "at least 5 visits"  for both pre-training and fine-tuning, and implement it as an option somewhere meaningful, #262.

I think that's all from this issue! Closing for now, feel free to re-open if not.
