### ISSUE TITLE
Separate .slice() and .as_slice() on patients

### ISSUE THREAD

**Issue by MartinBernstorff** [Aarhus-Psychiatry-Research/psycop-common#287]
isn't this just a list comprehension? Any reason to create a function

```
patient_slices = [p.to_patient_slice() for p in patient]
```

if you do want a function then I would rename it to:
```suggestion
def patients_to_slices(patients: Sequence[Patient]) -> Sequence[PatientSlice]:
```
as infinite could make it sound like a repeating generator.

_Originally posted by @KennethEnevoldsen in https://github.com/Aarhus-Psychiatry-Research/psycop-common/pull/274#discussion_r1365647007_

**Comment by KennethEnevoldsen** [comment]
Just use the list comprehension. No need for a function:

```
patient_slices = [p.as_slice() for p in patient]
```

More readable and flexible anyway.

**Comment by MartinBernstorff** [comment]
I still disagree re: intent. I don't think the list-comprehension communicates that this is just a type-recast, not a slicing. 

I guess we could separate it into two separate methods; `.slice(time_interval)` and `.as_slice()`, to separate the intents?

**Comment by KennethEnevoldsen** [comment]
I would say `as_slice()` communicates type recast (on the patient) and then the list comprehension communicates type recast on all the patients. I think the separation of `.slice()` and `.as_slice()` is an excellent idea.
