### ISSUE TITLE
Teste pytorch 2.1

### ISSUE THREAD

**Issue by MartinBernstorff** [Aarhus-Psychiatry-Research/psycop-common#306]
Re: https://github.com/Aarhus-Psychiatry-Research/psycop-ml-ops/issues/47#issuecomment-1780861290

Tænker processen er:
* Lave nyt miljø på Ovartaci
* Opdatere
* Køre tests
* Hvis alt passer, opdatere i `psycop-main`

@HLasse Noget for dig?

**Comment by HLasse** [comment]
On it

**Comment by HLasse** [comment]
Updated requirements and merged to main in #307
