### ISSUE TITLE
Create split based on region

### ISSUE THREAD

**Issue by HLasse** [Aarhus-Psychiatry-Research/psycop-common#314]
Includes methods for filtering visits based on the patient's first visit

Desired outcome:
- Easily able to switch between different types of splits (e.g. unique patients, geography, time ...)

Suggested implementation:
- Make a dataloader wrapper function, that takes a dataloader and a filter_fn that specifies how to filter that dataset.  

Example filter function 
```py
def filter_by_geography(dataloader: BaselineDataLoader, split: Iterable[Literal["øst", "midt", "nord"]]) -> pl.DataFrame
```

**Comment by MartinBernstorff** [comment]
We definitely want to consider how we implement this. E.g. we could have a preprocessing step that generates new splits, or something else.
