### ISSUE TITLE
tests: failing pytorch tests in docker container on M1

### ISSUE THREAD

**Issue by MartinBernstorff** [Aarhus-Psychiatry-Research/psycop-common#348]
![image](https://github.com/Aarhus-Psychiatry-Research/psycop-common/assets/8526086/06b1548f-affa-4b3c-8606-b2e388081ff6)

@KennethEnevoldsen, have you seen similar before?

![image](https://github.com/Aarhus-Psychiatry-Research/psycop-common/assets/8526086/35d39e1f-4b41-4486-9422-a75618e98a32)

**Comment by MartinBernstorff** [comment]
Might have to do with the Docker container as well. Further highlights the need for #338. 

@KennethEnevoldsen, have you run tests in the docker container? (No expectation that you had, just gathering information)

**Comment by KennethEnevoldsen** [comment]
I haven't run it on docker and the tests pass for me. I expect device/accelerator is "cpu", but if it is not you can try that out.

**Comment by MartinBernstorff** [comment]
Tests pass for me in .venv. Supports that the docker container is the culprit. Investigating.

**Comment by MartinBernstorff** [comment]
Current hypothesis is:
* Something with the base environment of the dev container. Trying with Python 3.11. If fails, proceed to next.
* Changes to code, since I must have run tests in the container previously. Git bisect my way through the last couple of weeks of commits to find a passing commit.

**Comment by MartinBernstorff** [comment]
Tests pass in Docker container in #350. It is an interaction effect between Apple Silicon and Docker container.

**Comment by MartinBernstorff** [comment]
Alternative hypothesis, Orbstack vs. Docker.

**Comment by MartinBernstorff** [comment]
Tests pass with Orbstack on Lasses computer. Possibilities are:

M1 x Orbstack
M1 x Container

Looking into those.

**Comment by MartinBernstorff** [comment]
The error occurs specifically in the forward pass of the `EncoderForClassification`, and only if `num_classes == 2` (e.g. not in the multiclass case).

I'm kind of at my wits end here.

**Comment by KennethEnevoldsen** [comment]
has the error been reproduced on another mac?

**Comment by MartinBernstorff** [comment]
Excellent point! And yep, I reproduced on Sara's 👍

**Comment by MartinBernstorff** [comment]
Try: 
- [x] Update pytorch, lightning and metrics. **Same error in the same place.**
- [X] Pytorch base image. No specific image for Mac. Tried latest from [here](https://hub.docker.com/r/pytorch/pytorch/tags). **Fails on M1 because of illegal instructions, most likely due to the image being built for AMD but running on ARM.** 

![image](https://github.com/Aarhus-Psychiatry-Research/psycop-common/assets/8526086/1bc85931-7870-4893-a7d9-b37431eb5b4d)

**Comment by KennethEnevoldsen** [comment]
Hmm et par andre ting som kunne hjælpe med debugging. Disable test virker som en fin idé for now, men det burde ikke være long term solution.

har du set:
https://docs.docker.com/desktop/troubleshoot/known-issues/

Har du forsøgt med et docker image med ARM64 tagget? (altså et image som ikke bliver fortolket at rosetta 2?

**Comment by MartinBernstorff** [comment]
> Disable test virker som en fin idé for now, men det burde ikke være long term solution.
Jeg er helt enig. De er kun disabled lokalt på M1 i containers, så main er stadig 'beskyttet', men det er ikke en fed løsning.

> Har du forsøgt med et docker image med ARM64 tagget?
Alle officielle python images bliver bygget til arm: 
![image](https://github.com/Aarhus-Psychiatry-Research/psycop-common/assets/8526086/d78b8b56-ef09-4c92-a2e3-465e10fc038e)

Man skal eksplicit override, hvis man vil bruge Rosetta 2 :-)

**Comment by MartinBernstorff** [comment]
Hmm, så vi er ikke kommet væsentligt nærmere en løsning her. @KennethEnevoldsen, er det acceptabelt at Pytorch development foregår i `.venvs`? 

Alternativt, har vi så andre ting at forsøge? F.eks. opdatere pytorch, lightning etc. og rebuilde periodisk? Så kan jeg sætte et cron job op der gør det på en PR en gang hver 14. dag el. lign.

**Comment by KennethEnevoldsen** [comment]
Jeg bruger ikke docker containeren så har ikke noget problem med det foregår i venv - så længe det bliver testet i ci.
