### ISSUE TITLE
feat: implement classification and remove type ignore

### ISSUE THREAD

**Issue by MartinBernstorff** [Aarhus-Psychiatry-Research/psycop-common#380]
```
class BinaryClassification(ProblemType): # type: ignore # TODO: Implement classification and remove type ignore
```

https://github.com/Aarhus-Psychiatry-Research/psycop-common/blob/728970647c6f8e865f9e002075a53f19d24c9067/psycop/common/model_training_v2/problem_type/problem_type_base.py#L32

**Comment by HLasse** [comment]
This is already done in #356

**Comment by MartinBernstorff** [comment]
Excellent! Make sure that the classification implementations subclass the `ProblemType` protocol.
