### ISSUE TITLE
Implement multilabelclassification and remove type ignore

### ISSUE THREAD

**Issue by MartinBernstorff** [Aarhus-Psychiatry-Research/psycop-common#381]
```
class MultilabelClassification(ProblemType): # type: ignore # TODO: Implement multilabelclassification and remove type ignore
```

https://github.com/Aarhus-Psychiatry-Research/psycop-common/blob/728970647c6f8e865f9e002075a53f19d24c9067/psycop/common/model_training_v2/problem_type/problem_type_base.py#L51

**Comment by HLasse** [comment]
Not high priority at the moment as no one uses it ( :( )
