### ISSUE TITLE
Specify how to ensure backwards-compatability on function changes

### ISSUE THREAD

**Issue by MartinBernstorff** [Aarhus-Psychiatry-Research/psycop-common#415]
We know historically that function signatures tend to change. We want to easily allow patching, e.g. add a new argument for a given function. 

This is basically adding a key to a dict before parsing, so perhaps this is not needed? What do you think @KennethEnevoldsen?

**Comment by KennethEnevoldsen** [comment]
from working on PR for spacy-transformers I would say something like:

1. If you add an argument without a default --> update version (copy the code, the old code can be moved to an [archive](https://pypi.org/project/spacy-legacy/))
2. if you add a argument with a default --> no problem there is the function can still be used as it used to
3. if you change functionality of the function (except for 2) --> same as 1

That requires a lot of user maintenance and alternative is to log the package which allow roll back to run the specific code.

Another option is to save the registered function used for a specific config in a separate file. The problem that that creates is that the function might rely on a function which might change in the main codebase.

None seems ideal, but it seems like we have to consider backward compatibility more than previously and I don't think there is a golden solution.

**Comment by MartinBernstorff** [comment]
@HLasse I completely agree with @KennethEnevoldsen here. I think #365 should point developers toward these decisions if the tests fail.

E.g.

"Some of the changes made in this PR breaks backwards-compatability. This means some historical configs will not be resolvable. To work around this:

If you added an argument to a function without a default: Create a copy of the function before the change and add it to the archive folder. The changed version of the function should be registered under a new name in the registry, e.g. `func_name_v2`."

I'm not sure how to make functionality-changes apparent. This will be indicated by failing tests, but might have to be collective/cultural knowledge. I don't think we can add it as an error message anywhere.

**Comment by KennethEnevoldsen** [comment]
Adding parsing of existing configs in the repo seems like a great first step, then there is two way we could resolve it:
1) update the config (e.g. add new argument)
2) create a versioned version of the function

I would not create CI specifically for checking it (i.e. provide a comment). It seems like the best way to solve a failing test. If it is a failing test of others code especially you would probably talk with the specific person as well.

Luckily in our case we don't have to guess, what potential configs exist, we know that they are all in the monorepo.

**Comment by MartinBernstorff** [comment]
@HLasse Kenneth raises a great point here; we could scrape the entire repo for `.cfg` files and check that they can be resolved. This requires a central registry, but that seems like a low barrier to my eyes 👍

**Comment by KennethEnevoldsen** [comment]
Seems like the easiest way (we could even forgo unifying if everyone just registers the config, but it might be easier to just find all .cfg files)

The problem is that we might have .cfg files that can't run in tests (e.g. if device is set to cuda, but we could work around that)

**Comment by MartinBernstorff** [comment]
I don't think we want to run every config, just resolve it. I'd assume we can modify most functions `__init__` to not have requirements about hardware, but let's cross that bridge when we get there 👍
