### ISSUE TITLE
feat: fill defaults from function signatures into .cfg

### ISSUE THREAD

**Issue by MartinBernstorff** [Aarhus-Psychiatry-Research/psycop-common#426]
https://thinc.ai/docs/api-config#fill

Allows us to specify defaults in the function signatures, and not relying on them in each .cfg. Makes the code nicer to read IMO.

But can also seem like magic if people just call a 'resolve' function, and suddenly the config is changed. Unsure how to make this best.

This is waiting on confection: https://github.com/explosion/confection/issues/47

When that is solved, we can reopen and merge #48.

**Comment by MartinBernstorff** [comment]
OTOH, if defaults exist, we should use them! I'll add this to the loader of baseschema.

**Comment by svlandeg** [comment]
Let us know whether [v0.1.5a0](https://pypi.org/project/confection/0.1.5a0/) fixes this? 🙏

**Comment by MartinBernstorff** [comment]
Absolutely! Will get on this next week 👍

**Comment by MartinBernstorff** [comment]
@svlandeg Seems fixed in #638! Waiting for review to merge.
