### ISSUE TITLE
Ensure that new registered functions are added to the `populate_baseline_registry` function

### ISSUE THREAD

**Issue by HLasse** [Aarhus-Psychiatry-Research/psycop-common#429]
As outlined in #365, we want to make sure that all configs for registered functions are usable and backwards compatible. 

To do this we intend to:
1. Find all registered functions
2. Convert them to a config 
3. Save config to disk if newly registered or updated
4. Check that all configs saved to disk can be resolved

This will raise an alert if we break something by e.g. changing or adding a variable. 

However, for this to work, `populate_baseline_registry` has to always be updated so we don't miss any registered functions. The question is, how do we ensure this. 

@KennethEnevoldsen, @MartinBernstorff  and I talked about this and came up with two solutions:

1) CI action that writes a comment if '@.+.register` is in the diff and prompts you to add it to the populate function
2) Emphasizing the importance of this among ourselves and the rest of developers, and keeping a keen eye out for this on PRs. 

We are very much open for better ideas and suggestions -- what do you think, Kenneth?

**Comment by KennethEnevoldsen** [comment]
Hmm I would probably do what is stated in #415. This seems way too complicated and put unreasonably restrictions on edits.

**Comment by MartinBernstorff** [comment]
One challenge #415 does not solve is historical configs.

E.g. the training run I did 3 months ago for T2D would only have the general experiment config in the repo (e.g. specifying the full hyperparameter spectrum), not each run's config. This means I could modify a function, adapt the config in the repo, and then the configs on Ovartaci remain broken. 

I'm not sure this is a big problem, and fine with ignoring it for now.

**Comment by HLasse** [comment]
Using the `registry.fill` method, this is actually not too difficult. I've made a PR that adds the functionality in #433. Would love if you would take a look.

**Comment by MartinBernstorff** [comment]
I think adding both will be a good idea, tracking the other idea in #437.
