### ISSUE TITLE
tests: find .cfgs in project and ensure they can be resolved

### ISSUE THREAD

**Issue by MartinBernstorff** [Aarhus-Psychiatry-Research/psycop-common#437]
_Originally posted by @KennethEnevoldsen in https://github.com/Aarhus-Psychiatry-Research/psycop-common/issues/415#issuecomment-1809865897_

**Goal**: All project .cfgs are parseable at all times. This ensures we do not break each others projects.

**Requirements**:
* All registries are fully populated (including project-specific registries)
    * Action: Add a "populate_all_registries" function
* .cfgs only fail to resolve if they are invalid
    * Action: Each project decides whether they want to test their .cfgs by implementing their own test
    * Dataloaders fail if the dataset does not exist on disk
        * Action: Disable validation if running in test (i.e. look for "validate" arg and set it to False or
        * Action: Change validation methods to log a failure, rather than raise an exception. I prefer this one, because it is less magical. But in use, it is nice that the inits raised exceptions.
        * Action: Can we catch the exception and, if it is a "MissingDatasetError", log during CI instead of failing? 
            * I think `confection` breaks it resolution, rather than continue and report errors afterwards, so this is probably not feasible. 

**Behavior:**
Given all .cfgs in repo

When resolving .cfgs 
And any .cfgs fails

Then a test fails

**Code:**
Populate registries -> 
Find all .cfgs ->
Resolve them all using something like "test registered cfgs" -> 
Collect failures -> 
If any failed, fail test and write meaningful message

**Comment by MartinBernstorff** [comment]
Waiting for #365.

**Comment by MartinBernstorff** [comment]
Goal: All project .cfgs are parseable at all times. This ensures we do not break each others projects, and that we can always re-train if we want to.

To get this done:
Populate registries -> Find all .cfgs -> Resolve them all using something like "test registered cfgs".

**Comment by MartinBernstorff** [comment]
@KennethEnevoldsen @HLasse Do you think this is still a good thing to add? And/or what do you think of the proposed implementation?

**Comment by MartinBernstorff** [comment]
@sarakolding @frillecode Would love you guys perspective as well!

**Comment by KennethEnevoldsen** [comment]
Hmm seq. models have a .cfg file that loads a dataset. So we wouldn't be able to resolve it

**Comment by MartinBernstorff** [comment]
Yeah, I proposed some possible solutions for that:
<img width="777" alt="image" src="https://github.com/Aarhus-Psychiatry-Research/psycop-common/assets/8526086/b121b5ae-7f94-4ef4-afba-9753f540cf30">

Or, if that doesn't solve it for your .cfg, move the loading outside of the `__init__` 👍

**Comment by KennethEnevoldsen** [comment]
I think it is easier to create a test in each subproject that test that if desired .cfg files are valid.

**Comment by MartinBernstorff** [comment]
That's a good alternate solution!

**Comment by KennethEnevoldsen** [comment]
I will close this one then

**Comment by MartinBernstorff** [comment]
Um, I think it still makes sense to have a shared solution to this, and then each project can decide whether to run the test. 

E.g. the implementation is in common, the test itself is in the project. I'll get to that sometime next week.
