### ISSUE TITLE
fix: log text representation of config

### ISSUE THREAD

**Issue by MartinBernstorff** [Aarhus-Psychiatry-Research/psycop-common#448]
https://github.com/Aarhus-Psychiatry-Research/psycop-common/blob/6a47c600badfddfc43b9bb4fd0ebb186677eb972/psycop/common/model_training_v2/config/baseline_pipeline.py#L8

**Comment by MartinBernstorff** [comment]
Goal: Allow filtering of runs based on configs. But is that even a thing in mlflow?

**Comment by KennethEnevoldsen** [comment]
Why not simply use registry.fill and then flatten?
