### ISSUE TITLE
tests: registry resolution does not error if previously assigned key no longer exists

### ISSUE THREAD

**Issue by MartinBernstorff** [Aarhus-Psychiatry-Research/psycop-common#456]
@HLasse I didn't get an error that 'prefix_count_validator' no longer exists in the registries. Perhaps we want the generated placeholders to include addressing? E.g.:

```cfg
[placeholder]
@preprocessing = "prefix_count_validator"
```

_Originally posted by @MartinBernstorff in https://github.com/Aarhus-Psychiatry-Research/psycop-common/pull/455#discussion_r1397351400_

**Comment by HLasse** [comment]
Raise an error if no @ in file
