### ISSUE TITLE
ci: require snyk test before merge

### ISSUE THREAD

**Issue by MartinBernstorff** [Aarhus-Psychiatry-Research/psycop-common#502]
Otherwise, we can still merge if snyk tests are failing.

This is set in "branch protection rules"; @sarakolding, this is a quick setting to change, but I think it's important you get hands-on experience here :-)

**Comment by sarakolding** [comment]
good point, think i fixed it now 🐒

**Comment by MartinBernstorff** [comment]
Excellent work 👍
