### ISSUE TITLE
Add 'on_training_end' to loggers

### ISSUE THREAD

**Issue by HLasse** [Aarhus-Psychiatry-Research/psycop-common#510]
We would like to be flexible on what we do post-training - e.g. Just logging the metric, or saving the pipe to disk.

One option could be to add a required 'on_training_end' function to the loggers that would be called after training and could be configured based on the individual loggers and the needs of the user. 

Could also add a PostTraining class that handles this, or something completely different. Very open for ideas

**Comment by MartinBernstorff** [comment]
This is interesting! Given the broad range of possible use-cases (which would need different inputs), we probably want different protocols here. 

I think a good start is to enumerate some of the use-cases we want:
* Saving the pipe (ArtifactSaver?)
* Logging the metric (Logger)

Anything else here?

**Comment by HLasse** [comment]
Yeah, I think that's all I ended up with as well. Unless someone would want to save some other artifacts (e.g. plots) to MLFlow or something -- but pipe and metric seem like the major ones

**Comment by MartinBernstorff** [comment]
Okay to close this as "not needed"?

**Comment by HLasse** [comment]
Yep, covered by other issues
