### ISSUE TITLE
Clean up CI

### ISSUE THREAD

**Issue by KennethEnevoldsen** [Aarhus-Psychiatry-Research/psycop-common#512]
We have done quite a lot to clean up the CI. What are some meaningful changes that are left? I think we need:

```[tasklist]
### Tasks
- [x] [ ] Linting workflow (remove PR comments)
- [x] [ ] Type-check workflow (remove PR comments)
```

Feel free to agree, disagree, and add to this.

**Comment by KennethEnevoldsen** [comment]
@MartinBernstorff anything else we are missing?
@sarakolding are there any of the workflows we have now that are unclear / need more documentation?

**Comment by sarakolding** [comment]
1. Linting is the same is pre-commit?
2. What does the test_post_coverage_comment do?

**Comment by KennethEnevoldsen** [comment]
Pre-commit is actions run before committing (this could include testing, linting, static type checking etc.) in our case it is mostly linting though.

so the pre-commit ci == linting in our case, but it might be more clear what it does it we call it linting (and then in the script call pre-commit). @MartinBernstorff and I discussed that we could potentially go away from pre-commit (but it makes linting quite easy as it bundles a lot of workflows in one).

> What does the test_post_coverage_comment do?

I believe it created a message with coverage (@MartinBernstorff). Might be worth renaming it so `create_coverage_comment`, the fact that it is run after the test is then just specified in the file.

**Comment by sarakolding** [comment]
> so the pre-commit ci == linting in our case, but it might be more clear what it does it we call it linting (and then in thee script call pre-commit).

I think calling it linting would make more sense - that also seems to be the way we do it with other tasks (i.e. naming according to task, not specific package).

> @MartinBernstorff and I discussed that we could potentially go away from pre-commit (but it makes linting quite easy as it bundles a lot of workflows in one).

As far as I can tell, the pre-commit workflow includes ruff, black and check-yaml?

**Comment by KennethEnevoldsen** [comment]
Yep also removed that from the swift template.
