### ISSUE TITLE
snyk is pricey

### ISSUE THREAD

**Issue by sarakolding** [Aarhus-Psychiatry-Research/psycop-common#514]
have just received an email that we have already spent 120 out of our 200 snyk scans this month... if we want unlimited scans, we need to buy a license for the organisation. alternatively, @HLasse suggested we could do the scans, only when merging into main (hopefully <200 times a month). thoughts, @MartinBernstorff @KennethEnevoldsen?

**Comment by HLasse** [comment]
Don't know if the above is possible to do, though

**Comment by KennethEnevoldsen** [comment]
Ahh, this is frustrating. Another option would be to only run it on changes to the requirements*.txt files. I think that keeps all the benefits of the current approach and saves us a subscription

**Comment by KennethEnevoldsen** [comment]
> Don't know if the above is possible to do, though

In GitHub CI it is very easy to enable workflow only on push to main branch.

**Comment by sarakolding** [comment]
will take a look at it tomorrow

**Comment by MartinBernstorff** [comment]
Completely agree with @KennethEnevoldsen here. We can gate the snyk workflow so that it only runs if any of the requirements have changed since main. E.g. using `filetype_modified_since_head` with `.txt`.
