### ISSUE TITLE
ci: run snyk every 2 weeks, irrespective of requirements.txt

### ISSUE THREAD

**Issue by MartinBernstorff** [Aarhus-Psychiatry-Research/psycop-common#539]
Our current implementation doesn't catch if new vulnerabilities are found in packages we already have installed. 

We need to be alerted in some way, so we can handle it.

@sarakolding, something you would be up for? :-)

**Comment by sarakolding** [comment]
add weekly snyk run - if it fails, email everyone @MartinBernstorff ?
