### ISSUE TITLE
feat: abstract interfaces for tasks (finetuning and MLMModule)

### ISSUE THREAD

**Issue by MartinBernstorff** [Aarhus-Psychiatry-Research/psycop-common#540]

**Comment by MartinBernstorff** [comment]
I'm not sure this is possible. E.g. say we want to create a `ModelforMLM` protocol like this:

```python
class ModelForMLM(Protocol):
    def training_step(
        self,
        batch: BatchWithLabels,
        batch_idx: str,
    ):
        ...
```

This does not align with `pl.LightningModule`, since its `training_step` is type-hinted as:
```python
def training_step(self, *args: Any, **kwargs: Any) -> STEP_OUTPUT:
```

If we want valid overrides, we cannot both inherit from `pl.LightningModule` and specify the required inputs in the `ModelForMLM` protocol. This is a meaningful problem for composability.

Maybe we could fix this with another layer of indirection by:
* Subclassing `pl.LightningModule`:
```python
class LightningModuleForMLM(pl.LightningModule):
    def training_step(
        self,
        batch: BatchWithLabels,
        batch_idx: str,
    ):
        ...
 ```
 
 * And then using that for inheritance:     
 ```python
 class BEHRTForMaskedLM(ModelForMLM, LightningModelForMLM)
 ```
 
 What do you think @KennethEnevoldsen?

**Comment by KennethEnevoldsen** [comment]
Sounds great would love!

**Comment by KennethEnevoldsen** [comment]
PatientSliceModule

**Comment by KennethEnevoldsen** [comment]
(tror der kan laves en fælles for både finetuning module og MLM module)

**Comment by MartinBernstorff** [comment]
Både `BEHRTForMaskedLM` og `EncoderForClassification` tager `BatchWithLabels` i deres `training_step`.

```python
@dataclass
class BatchWithLabels:
    """
    A batch with labels.

    Attributes:
        inputs: A dictionary of padded sequence ids. Shape (batch_size, sequence_length).
        labels: A tensor of labels for the batch. Shape (batch_size, num_classes).
    """

    inputs: dict[str, torch.Tensor]
    labels: torch.Tensor

    def __iter__(self) -> Iterator[dict[str, torch.Tensor] | torch.Tensor]:
        return iter((self.inputs, self.labels))
```
