### ISSUE TITLE
feat: why are filter methods called twice?

### ISSUE THREAD

**Issue by MartinBernstorff** [Aarhus-Psychiatry-Research/psycop-common#549]
Should be doable through tests.

We get some `tqdm` calls that are one item per call. Why is that? Can we avoid it?

**Comment by MartinBernstorff** [comment]
During a finetuning, seems it is called in:
* `create_behrt_embedder -> BEHRTEmbedder.fit`
* `dataset.filter_patients -> EncoderForClassification.filter_and_reformat`

A few questions:
* During a finetuning, shouldn't the embedder already by fit? In other words, could it be problematic that we re-fit it? (E.g. if more diagnoses are added to the vocabulary, the index of a given diagnosis could shift, changing the meaning of all of them in the sequence.

**Comment by MartinBernstorff** [comment]
@KennethEnevoldsen See the question above. Is it a problem we re-fit the embedder?

**Comment by KennethEnevoldsen** [comment]
We should not refit the embedder during fine-tuning when initializing from a pre-trained model.

**Comment by MartinBernstorff** [comment]
> that is probably a good reason to keep it out of train()

Not sure I understand, could you elaborate here?

**Comment by KennethEnevoldsen** [comment]
Having it in `train()`would lead to it being `refit` during fine-tuning. That is not what we want.

**Comment by MartinBernstorff** [comment]
Not necessarily, I've submitted a suggestion in #583.
