### ISSUE TITLE
paper: methods-section for applying BEHRT to CVD

### ISSUE THREAD

**Issue by MartinBernstorff** [Aarhus-Psychiatry-Research/psycop-common#577]

**Comment by KennethEnevoldsen** [comment]
Outline description:

Methods:
> We additionally compare with a BEHRT model architecture [cite]. BEHRT is a pre-trained transformer architecture that is pre-trained to estimate statistical co-occurrence patterns between diagnoses and then fine-tuned for prediction of CVD. The pre-train, then fine-tune paradigm have been extremely popular in the deep learning literature for modeling sequence both in medical [cite_transformehr, cite_behrt] and non-medical domains [cite_bert, cite_wav2_vec2.0].
> As there exists no publicly available pre-trained BEHRT we pre-train our own model using all the hyperparameters specified in the original paper [cite_behrt] and the follow-up paper [cite_hibert]. Where no hyperparameters are specified we use the ones specified in the BERT [cite_bert] from which BEHRT is derived \footnote{We did reach out to the authors regarding the used hyperparameters but we did not get a response.}. 
> For our fine-tuned we searched over a meaningful set of hyperparameters {add here}. These includes the suggested hyperparameters for BEHRT [cite].

> To get a full overview of the hyperparamter see Appendix {Appendix-I}.

Results:

> | Model                             | ROCAUC  |
> | --------------------------------- | ------- |
> | BERHT (our implementation) | {score} |

**Comment by MartinBernstorff** [comment]
Have edited a bit here: https://docs.google.com/document/d/1AX_1plCltMobXZVFRBTVV4r1GTCcCQw73r3H4hWYqXA/edit?usp=sharing

**Comment by KennethEnevoldsen** [comment]
Perfect accepted everything - what's left is minor.

**Comment by HLasse** [comment]
This looks like it can be closed?
