### ISSUE TITLE
refactor: `iddatafilter` should only take split_ids as input

### ISSUE THREAD

**Issue by MartinBernstorff** [Aarhus-Psychiatry-Research/psycop-common#621]
https://github.com/Aarhus-Psychiatry-Research/psycop-common/blob/07049d1eb6c8dd8bf2232361a07c3d47382b3ea9/psycop/common/model_training_v2/trainer/data/data_filters/original_ids.py#L14

**Comment by MartinBernstorff** [comment]
@HLasse I think we should start migrating to only using `split_ids` as a `set[str]` when splitting across all projects. 

This would also dramatically simplify the class. Let me know what you think 👍

**Comment by HLasse** [comment]
There's a complication in the regional/geographical split, as we need to do two things: 
1. Only keep pred times from the desired patients
2. Drop pred times after a move to a different region

This would require an additional step (which should be mandatory when using the regional split), so I'm unsure if it's the best way forward
