### ISSUE TITLE
dev: pull main on container startup

### ISSUE THREAD

**Issue by MartinBernstorff** [Aarhus-Psychiatry-Research/psycop-common#629]
Not feasible to do in the background. `git fetch origin` only gets the data, it doesn't merge it. 

Merging requires checking out the branch, which means we'd have to remember where we started, and then go back again. This has a higher likelihood of causing problems.

@HLasse I think a wontfix is the right move here, let me know if you disagree :-)

**Comment by HLasse** [comment]
Agreed, sounds like it's not worth it
