### ISSUE TITLE
refactor: split IDDataFilter into a StratifiedByOutcomeSplitter and a IDDataFilter?

### ISSUE THREAD

**Issue by MartinBernstorff** [Aarhus-Psychiatry-Research/psycop-common#657]
```
# TODO: Split IDDataFilter into a StratifiedByOutcomeSplitter and a IDDataFilter?
```

https://github.com/Aarhus-Psychiatry-Research/psycop-common/blob/9499887a3c007e82bcc69c9d93eb874d4485e6ba/psycop/common/model_training_v2/trainer/data/data_filters/original_ids.py#L14

Seems the two concerns are somewhat unrelated? Would also markedly simplify the function signature. What do you think? @HLasse

**Comment by HLasse** [comment]
I get a 404 on the link so not completely sure what you're referring

**Comment by HLasse** [comment]
👍
