### ISSUE TITLE
feat: use separate geographical splits for train and test

### ISSUE THREAD

**Issue by sarakolding** [Aarhus-Psychiatry-Research/psycop-common#851]
train and val data are loaded separately and then undergo identical preprocessing. since splitting by geography is a preprocessing step, we cannot train on one geographical split and validate on another.

**Comment by sarakolding** [comment]
thoughts: separate preprocessing pipelines for train and val, in addition to separate loaders?
separate data loaders for old splits vs geographical splits?

**Comment by MartinBernstorff** [comment]
I've thought a bit about this, and I think separating the preprocessing pipelines is an excellent idea. If we want to then train and test with the same pipeline, we just specify it in its own variable, and then pass it as both train-pipeline and test-pipeline.

This shouldn't require separate loaders; we just load all the data for both pipelines, and filter it according to geographical split.

Does this sound good? 👍

**Comment by MartinBernstorff** [comment]
If we want to, we can also create a thin wrapper that passes a single pipeline to both train and test. But we can talk about that.

**Comment by sarakolding** [comment]
@HLasse disagreed. can we talk about it?
