### ISSUE TITLE
refactor: move result logging to `train_baseline_model_from_schema`

### ISSUE THREAD

**Issue by MartinBernstorff** [Aarhus-Psychiatry-Research/psycop-common#866]
By results, I mean logging the `TrainingResult`, i.e. the optimised metric and the "eval_df".

Currently, we duplicate it in both of the trainers. Since result logging is needed no matter which trainer you use, and all trainers must return a `TrainingResult`, it think it's better to move this one layer out.

What do you think @HLasse?

**Comment by HLasse** [comment]
Yep, seems reasonable!
