### ISSUE TITLE
Remove Hydra

### ISSUE THREAD

**Issue by MartinBernstorff** [Aarhus-Psychiatry-Research/psycop-common#98]
Benefits:
* Changes to config object is caught by pyright, see #97 

Challenges:
* Using both GPU and CPU at the same time requires parallelising across models, which is not natively supported by Optuna's `n_jobs`

Required changes:
* Specify config objects in pure Python
* Implement Optuna-based hyperparameter searching loop
    * Lasse indicated that Optuna might have an `n_processes` option to allow for faster training and easier parallelisation.

**Comment by HLasse** [comment]
Seems like we would have to setup some sort of SQL database while the Optuna study is running. Not sure as to the amount of effort required to make it work https://github.com/optuna/optuna/issues/2202
https://optuna.readthedocs.io/en/stable/tutorial/10_key_features/004_distributed.html

**Comment by MartinBernstorff** [comment]
Doable with SQLite I think, since we don't need distributed training (multi-node), only multiple processes 👍
